-- BUNSEKI-018A.3. Additive PostgreSQL migration. Never run against production without approval.
CREATE TABLE IF NOT EXISTS teachers (id BIGSERIAL PRIMARY KEY,user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','inactive')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS academic_periods (id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,start_date DATE,end_date DATE,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','active','closed')),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subjects (id BIGSERIAL PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL UNIQUE,description TEXT,category TEXT,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS courses (id BIGSERIAL PRIMARY KEY,subject_id BIGINT NOT NULL REFERENCES subjects(id),academic_period_id BIGINT NOT NULL REFERENCES academic_periods(id),code TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(academic_period_id,code),UNIQUE(id,academic_period_id));
CREATE TABLE IF NOT EXISTS teacher_courses (teacher_id BIGINT NOT NULL REFERENCES teachers(id),course_id BIGINT NOT NULL REFERENCES courses(id),role TEXT NOT NULL DEFAULT 'instructor',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),PRIMARY KEY(teacher_id,course_id));
CREATE TABLE IF NOT EXISTS parallels (id BIGSERIAL PRIMARY KEY,course_id BIGINT NOT NULL REFERENCES courses(id),code TEXT NOT NULL,name TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(course_id,code),UNIQUE(course_id,id));
CREATE TABLE IF NOT EXISTS cohorts (id BIGSERIAL PRIMARY KEY,course_id BIGINT NOT NULL REFERENCES courses(id),code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,research_group TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(course_id,id));
CREATE TABLE IF NOT EXISTS enrollments (id BIGSERIAL PRIMARY KEY,student_user_id INTEGER NOT NULL REFERENCES users(id),course_id BIGINT NOT NULL REFERENCES courses(id),parallel_id BIGINT NOT NULL,cohort_id BIGINT NOT NULL,status TEXT NOT NULL DEFAULT 'active',source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual','bulk_import','legacy_reconciled')),enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(student_user_id,cohort_id),FOREIGN KEY(course_id,parallel_id) REFERENCES parallels(course_id,id),FOREIGN KEY(course_id,cohort_id) REFERENCES cohorts(course_id,id));
CREATE TABLE IF NOT EXISTS legacy_academic_reconciliation (id BIGSERIAL PRIMARY KEY,user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),enrollment_id BIGINT REFERENCES enrollments(id),status TEXT NOT NULL DEFAULT 'pending',reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments(student_user_id); CREATE INDEX IF NOT EXISTS idx_enrollments_course ON enrollments(course_id);
INSERT INTO subjects(code,name) VALUES ('ALG-ELEM','Álgebra Elemental / Precálculo'),('ALG','Álgebra'),('EST','Estadística'),('CALC-DIF','Cálculo Diferencial'),('CALC-INT','Cálculo Integral') ON CONFLICT (code) DO NOTHING;
